feature/serviceprovider
regnerisch/laravel-beyond pull request #22
Opened 2022-04-28 15:36 UTC by nilsvennemann

Since I have a hunch that this will bother many I thought I'd add something. I hope that I have done a good job and thus service providers can also be created in `src/App/Providers` since `php artisan make:provider` does this in the normal App/ folder otherwise. Thanks.

2022-04-28 15:43 UTC, alexgaal requested changes
Please change accordingly my comments. @regnerisch PR looks fine to me. What do you think?

2022-04-28 15:43 UTC, alexgaal commented on src/Commands/MakeServiceProviderCommand.php
> +    protected $signature = 'beyond:make:service:provider {className}';
Please change signature to `beyond:make:provider`.

2022-04-28 15:43 UTC, alexgaal commented on src/LaravelBeyondServiceProvider.php
> +                MakeServiceProviderCommand::class,
Please sort this alphabetically.

2022-04-28 15:51 UTC, alexgaal commented on src/LaravelBeyondServiceProvider.php
> +                MakeServiceProviderCommand::class,
This is not resolved @nilsvennemann.

2022-04-28 15:54 UTC, alexgaal commented on src/LaravelBeyondServiceProvider.php
> +                MakeServiceProviderCommand::class,
`MakeRouteCommand` should be before `MakeServiceProviderCommand`.

2022-04-28 15:56 UTC, alexgaal approved these changes
@regnerisch Approved by me. Please check on that PR.

2022-04-28 19:17 UTC, regnerisch commented
Documentation is missing. Everything else seems to be good.

2022-04-29 05:04 UTC, alexgaal approved these changes

2022-04-29 05:04 UTC, merged