Remove old method fromRequest()
regnerisch/laravel-beyond pull request #58
Opened 2022-08-22 15:06 UTC by thewebartisan7

From v3 of Spatie DTO package seem that fromRequest() it's not anymore the way to be used.

I checked readme of v2 and I found it, but in v3 it's not anymore there.

2022-08-22 15:07 UTC, thewebartisan7 commented
We could optionally pass property and type via command line, and/or an option to make it Strict.

2022-08-23 17:40 UTC, regnerisch commented
I currently use this method like so: `MyData::fromRequest($request)`

So your idea is to just make `new MyData($request->all())` Is this right?

I'm not sure but I would say my version (with fromRequest) seems to be a little more cleaner. Also you can easily overwrite things inside this method. I think wie should stay with that method - you do not need to use it, it is optional :)

2022-08-24 05:00 UTC, thewebartisan7 commented
But how is an example of your MyData class? 

Because the docs of new version show just the list of properties with value casts, mapping and strict DTOs.
By using a method fromRequest() I think that casting and mapping that you can add via attribute will not even works. Almost for me didn't worked.

By passing via constructor you don't need to worries how properties are mapped (from request to class properties), just pass an array or via named arguments.

In docs it's written:

> The goal of this package is to make constructing objects from arrays of (serialized) data as easy as possible

For example a simple UserData:

```php
<?php

namespace Domain\Users\DataTransferObjects;

use Spatie\DataTransferObject\DataTransferObject;

class UserData extends DataTransferObject
{
    public string $name;

    public string $email;

    public ?string $password;
}
```

Then:

```php
// Controller
$updateUserAction->execute($user, $request->validated());
// or
$updateUserAction->execute($user, $request->only(["name", "email", "password"]));

// Action
$userData = new UserData($data);
$userData->all();

$userData
    ->only('name')
    ->toArray();
    
$userData
    ->except('name')
    ->toArray();
```

Also passing directly $request to DTO, that means that you first need to pass $request to Action, and the Action pass $request to DTO, when you are using Action.

2022-08-24 05:33 UTC, regnerisch commented
You did not read the book right? You will have something like this: 

```php
// Controller
public function update(User $user, UpdateUserRequest $request, UpdateUserAction $action)
{
    $data = UserData::fromRequest($request);

    $user = $action->execute($user, $data);

    return new UserResource($user);
}

// DTO
public string $email;
public string $givenName;
public string $familyName;
public ?int $somethingSpecial

public static function fromRequest(StoreUserRequest|UpdateUserRequest $request): self
{
    return new self(array_merge(
        $request->validated(),
        ['somethingSpecial' => doSomething()]
    ));
}

// Action
public function execute(User $user, UserData $data)
{
    $user->update($data->toArray());

    return $user->refresh();
}
```
What `fromRequest` do, is ensuring that the DTO gets the right request(s) for filling the attributes. As you can see, with `new self(...)` we do nothing else than you with `new UserData(...)`.

2022-08-24 06:40 UTC, thewebartisan7 commented
Now that you show me, I remember that I saw the static constructor.. I tested and it works fine.. Not sure what I did wrong when I tried.

However, I am not sure about this approach.. Are we not mixing application and domain layer in this way?

Also why not delegate everything to action for create the DTO?

If you need to do the same for API, Web and Console for example, then you need to create new instance of DTO each time.. of course it's not a big deal, just one line of code, but it's not scope of action to encapsulate all this logic?

Anyway no problem for me, I can just remove fromRequest() from generated DTO.

2022-08-24 06:46 UTC, alexgaal commented
Why would it mix application and domain more than using Actions? I call an Action within an applications controller, it's the same for DTOs I think. Since it's editable anyway I'd prefer to keep this in our package.

2022-08-24 07:16 UTC, thewebartisan7 commented
I mean that passing $request to DTO, you are mixing request (application) with DTO (domain). So domain depend on application code.

2022-08-24 16:48 UTC, regnerisch commented
My example above is like the Laravel Beyond CRUD book specify it. So we definitely will keep this behavior. If you think this is wrong or breaks the app/domain separation you are free to implement it your own way :)

2022-08-24 17:02 UTC, thewebartisan7 commented
> My example above is like the Laravel Beyond CRUD book specify it. So we definitely will keep this behavior. If you think this is wrong or breaks the app/domain separation you are free to implement it your own way :)

I am not thinking it's wrong, I know that with follow strictly DDD it's hard with Laravel.
I am just trying to find the better way, because it breaks the separation of domain and app, I hope you agree?

Because I want to have single DTO for my application (Web, Admin, API, Console, etc).. but when this application has different Request rules, then you need a new DT0, or as you do allow all the Requests as parameter of the fromRequest.

That it break separation of domain and app it's admitted also by author of Laravel Beyond CRUD in his free article, he wrote:

"Obviously, mixing application-specific code within the domain isn't the best of ideas. However, it does have my preference.", referring to that fromRequest inside DTO. See here https://stitcher.io/blog/laravel-beyond-crud-02-working-with-data

2022-08-24 21:05 UTC, regnerisch commented
I see your point, we should add a data factory command and move the `fromRequest` method to the factory. Adding a flag to specify which Model should be used. Feel free to submit a PR.

2022-08-25 07:42 UTC, regnerisch requested changes
As discussed we will add a new DTO factory command and move the `fromRequest` method to the factory stub.

2022-08-25 11:57 UTC, thewebartisan7 commented
> As discussed we will add a new DTO factory command and move the `fromRequest` method to the factory stub.

Ok. If you want I can do.

We could also use the same command but just with option:

`php artisan beyond:make:dto MyDTO --factory`

Which will create the factory for MyDTO.

Without option, will not create the factory.

2022-08-29 10:47 UTC, regnerisch commented
Wouldn't it a little bit strange to do something like `beyond:make:dto User/UserData --factory=Admin/User/UserFactory`? But feel free to implement it your way. I will take a look afterwards.

2022-08-29 11:31 UTC, thewebartisan7 commented
> Wouldn't it a little bit strange to do something like `beyond:make:dto User/UserData --factory=Admin/User/UserFactory`? But feel free to implement it your way. I will take a look afterwards.

I mean even without passing factory FQCN as we can build it from App and Domain.

Example if DTO class name is UserData under `User` domain and `Admin` app, then we can create the factory inside `{App}/{Domain}/DartaFactories/{Domain}DataFactory`.

2022-08-30 11:08 UTC, closed without merging