DTO Factory flag
regnerisch/laravel-beyond pull request #65
Opened 2022-08-30 12:46 UTC by thewebartisan7

As discussed here https://github.com/regnerisch/laravel-beyond/pull/58 this PR add a new optional flag --factory in DTO command. When added will be create a new class in App for DTO Factory.

Usage:

```bash
# Will ask Domain, Class name and App
beyond:make:dto --factory

# Will ask App and create the factory in 
# `src/App/Web/User/DataFactories/UserDataFactory.php` (Supposely App provided is "Web")
beyond:make:dto User/UserData --factory
```

A DTO like this:

```php
<?php

namespace Domain\Users\DataTransferObjects;

use Spatie\DataTransferObject\DataTransferObject;

class MyData extends DataTransferObject
{
    // Add properties here
}
```

Will create a DTO Factory:

```php
<?php

namespace App\Admin\Users\DataFactories;

use Illuminate\Http\Request;

use Domain\Users\DataTransferObjects\MyData;

class MyDataFactory
{
    public static function fromRequest(Request $request): MyData
    {
        return new MyData($request->all());
    }
}
```

2022-08-30 13:10 UTC, thewebartisan7 commented
I forgot.. I was thinking of a way to handle also others `from` method, example `fromModel()` and a generic `from()` (as from array).

So it's look like:

```php
<?php

namespace App\Admin\Users\DataFactories;

use Illuminate\Http\Request;
use Illuminate\Database\Eloquent\Model;
use Domain\Users\DataTransferObjects\MyData;

class MyDataFactory
{
    public static function from(array $array): MyData
    {
        return new MyData($array);
    }

    public static function fromRequest(Request $request): MyData
    {
        return new MyData($request->all());
    }

    public static function fromModel(Model $model): MyData
    {
        return new MyData($model->toArray());
    }
}
```

Or even:

```php
<?php

namespace App\Admin\Users\DataFactories;

use Illuminate\Http\Request;
use Illuminate\Database\Eloquent\Model;
use Domain\Users\DataTransferObjects\MyData;

class MyDataFactory
{
    public static function from(array $array): MyData
    {
        return new MyData($array);
    }

    public static function fromRequest(Request $request): MyData
    {
        return self::from($request->all());
    }

    public static function fromModel(Model $model): MyData
    {
        return self::from($model->toArray());
    }
}
```

Or even a base DTO Factory with from() method, that is extended by others, which could be in Domain.

What you think?

2022-09-01 09:46 UTC, regnerisch requested changes

2022-09-01 09:46 UTC, regnerisch commented on stubs/data-transfer-object.stub
> +    // Add properties here
Please remove the comment. I want to keep things clean just keep the `//`.

2022-09-01 09:46 UTC, regnerisch commented on src/Commands/MakeDataTransferObjectCommand.php
> +    protected $signature = 'beyond:make:dto {name?} {--overwrite} {--factory}';
Please remove the flag again, I do not like how the flag is handled. I know this is currently the only possible solution but I will develop a better way in v4. So for now we will drop the `factory`-flag and add it again in v4.

2022-09-01 09:46 UTC, regnerisch commented on src/Commands/MakeDataTransferObjectCommand.php
> +            if ($factory) {
Please remove, see previous reason.

2022-09-01 11:21 UTC, thewebartisan7 commented
As I understand the only thing you want to do for now is to remove fromRequest() from the DTO stub, right?

2022-09-01 11:23 UTC, thewebartisan7 commented
If you want create a separated command, then also in that case you need to specify for which DTO you want to create the Factory, so like --dto=MyData

Either way you need to mix classes, if that is not what you like.

2022-09-01 11:52 UTC, regnerisch commented
> As I understand the only thing you want to do for now is to remove fromRequest() from the DTO stub, right?

Yes. For now I would recommend to add just a factory command and not a flag. If you need a factory you have to explicit call the factory command.

2022-09-23 09:21 UTC, alexgaal commented
See #71.

2022-09-23 09:21 UTC, closed without merging