Invokable controller option
regnerisch/laravel-beyond pull request #67
Opened 2022-09-03 09:25 UTC by dimitribocquet

You can now create an invokable Controller by passing `--invokable` option.

2022-09-03 14:33 UTC, regnerisch requested changes
Please also add the new flag inside documentation at README.md

2022-09-03 14:33 UTC, regnerisch commented on src/Commands/MakeControllerCommand.php
> -            $stub = $api ? 'controller.api.stub' : 'controller.stub';
https://www.php.net/manual/en/control-structures.match.php

```php
 $stub = match(true) {
  $api => 'controller.api.stub',
  $invokable => 'controller.invokable.stub'
  default => 'controller.stub'
};
```

2022-09-21 14:20 UTC, dimzeta commented
Thank you for your review, that should be good now!

2022-09-22 06:11 UTC, regnerisch approved these changes

2022-09-22 06:11 UTC, merged